# Generated by Django 5.2.4 on 2025-08-17 15:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_alter_order_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True, verbose_name='Payment ID')),
                ('gateway', models.CharField(choices=[('flutterwave', 'Flutterwave'), ('paystack', 'Paystack'), ('bank_transfer', 'Bank Transfer')], max_length=50, verbose_name='Payment Gateway')),
                ('gateway_transaction_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Gateway Transaction ID')),
                ('gateway_reference', models.CharField(blank=True, max_length=200, null=True, verbose_name='Gateway Reference')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Payment Amount')),
                ('currency', models.CharField(default='NGN', max_length=3, verbose_name='Currency')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('successful', 'Successful'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='Payment Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Payment Date')),
                ('gateway_response', models.JSONField(blank=True, null=True, verbose_name='Gateway Response Data')),
                ('retry_count', models.PositiveIntegerField(default=0, verbose_name='Retry Count')),
                ('last_error', models.TextField(blank=True, null=True, verbose_name='Last Error Message')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['payment_id'], name='payments_pa_payment_6c9e39_idx'), models.Index(fields=['gateway_transaction_id'], name='payments_pa_gateway_2a3159_idx'), models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx'), models.Index(fields=['order', 'status'], name='payments_pa_order_i_a76289_idx')],
            },
        ),
    ]
