# Generated by Django 5.2.4 on 2025-08-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('flutterwave', 'Flutterwave'), ('paystack', 'Paystack'), ('whatsapp', 'WhatsApp Order'), ('bank_transfer', 'Bank Transfer'), ('cash_on_delivery', 'Cash on Delivery')], max_length=50, verbose_name='Payment Method'),
        ),
    ]
