# Generated by Django 5.2.4 on 2025-09-13 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_payment_method'),
        ('orders', '0002_alter_order_shipping_zip_code'),
    ]

    operations = [
    ]
